---
- import_tasks: multiuser.yml
  when: sysadmin_multi_user

- import_tasks: singleuser.yml
  when: not sysadmin_multi_user

- name: Fail if multiusers vars are not not set
  fail:
    msg: "sysadmin_multi_user must be set to true or false. If false, sysadmin_username must be set."
  when:
  - sysadmin_multi_user is not defined
  - sysadmin_multi_user is not boolean
  - sysadmin_multi_user is false and sysadmin_username is not defined
