---
- name: Install sudo command
  apt:
    pkg: sudo
    state: present

- name: Add SSH public keys to system administrators
  authorized_key:
    user: "{{ sysadmin_username }}"
    key: "{{ lookup('file', item.ssh_key) }}"
    state: "{{ item.state }}"
  when: item.state == "present"
  with_items: "{{ sys_admins }}"
